name: 'Generate Build Matrix'
description: 'Generates the build matrix for SageAttention wheels'
inputs:
  build_profile:
    description: 'Build profile (stable/default)'
    required: true
  os:
    description: 'Operating System (linux/windows)'
    required: true
  project:
    description: 'Project type (sage2/sage3)'
    required: true
outputs:
  matrix:
    description: "The JSON build matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - name: Generate Matrix
      id: set-matrix
      shell: bash
      run: |
        profile="${{ inputs.build_profile }}"
        os="${{ inputs.os }}"
        project="${{ inputs.project }}"
        
        echo "Generating matrix for Project: $project, OS: $os, Profile: $profile"

        # 1. Define Base Versions (Python|PyTorch|CUDA)
        declare -a base_versions=(
          "3.12|2.9.0|12.8.0"
          "3.12|2.9.0|12.9.0"
          "3.12|2.9.0|13.0.0"
          "3.12|2.9.0|13.1.0"
        )
        
        # 2. Select Project Configs
        arch_list=""
        project_prefix=""
        
        if [[ "$project" == "sage2" ]]; then
          project_prefix=""
          if [[ "$os" == "windows" ]]; then
             arch_list="7.0;7.5;8.0;8.6;8.7;8.9;9.0;10.0"
          else
             arch_list="7.0;7.5;8.0;8.6;8.7;8.9;9.0;10.0"
          fi
        elif [[ "$project" == "sage3" ]]; then
          project_prefix="Sage3 + "
          arch_list="10.0" 
        else
          echo "Error: Unknown project $project"
          exit 1
        fi

        # 3. Construct Candidate Builds with Display Names
        declare -a candidate_builds=()
        for version in "${base_versions[@]}"; do
             IFS='|' read -r python pytorch cuda <<< "$version"
             
             # Simplify CUDA version for display (12.8.0 -> 12.8)
             cuda_short=$(echo "$cuda" | cut -d. -f1,2)
             
             # Construct display: "Sage3 + PyTorch 2.9.0 + CUDA 12.8 + Python 3.12"
             display="${project_prefix}PyTorch ${pytorch} + CUDA ${cuda_short} + Python ${python}"
             
             # Stash in format: python|pytorch|cuda|display
             candidate_builds+=("$python|$pytorch|$cuda|$display")
        done

        # 4. Filter by Profile
        declare -a final_builds=()
        
        if [[ "$profile" == "default" ]]; then
          # Use only the first item (latest supported stable version)
          final_builds=("${candidate_builds[0]}")
        else
          # Stable / everything else -> All builds
          final_builds=("${candidate_builds[@]}")
        fi
        
        # 5. JSON construction
        matrix_json="["
        first=true
        for build in "${final_builds[@]}"; do
          IFS='|' read -r python pytorch cuda display <<< "$build"
          
          if [ "$first" = true ]; then
            first=false
          else
            matrix_json+=","
          fi
          
          # Construct JSON object
          matrix_json+="{\"python\":\"$python\",\"pytorch\":\"$pytorch\",\"cuda\":\"$cuda\",\"display\":\"$display\",\"arch_list\":\"$arch_list\"}"
        done
        matrix_json+="]"
        
        echo "matrix={\"include\":$matrix_json}" >> $GITHUB_OUTPUT
        echo "Build count: ${#final_builds[@]}"
        echo "$matrix_json" | jq .
