name: 'Generate Build Matrix'
description: 'Generates the build matrix for SageAttention wheels'
inputs:
  build_profile:
    description: 'Build profile (stable/default)'
    required: true
  os:
    description: 'Operating System (linux/windows)'
    required: true
  project:
    description: 'Project type (sage2/sage3)'
    required: true
outputs:
  matrix:
    description: "The JSON build matrix"
    value: ${{ steps.set-matrix.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - name: Generate Matrix
      id: set-matrix
      shell: bash
      run: ${{ github.action_path }}/generate_matrix.sh "${{ inputs.build_profile }}" "${{ inputs.os }}" "${{ inputs.project }}"
