# Hadolint configuration for SageAttention Dockerfiles
# See https://github.com/hadolint/hadolint for rule documentation

ignored:
  # Windows-specific exceptions
  - DL3008  # Pin versions in apt-get install (not applicable to Windows)
  - DL3009  # Delete apt-get cache (not applicable to Windows) 
  - DL3015  # Avoid additional packages (winget doesn't have --no-install-recommends)
  - DL4006  # Not related to SHELL usage in Windows containers
  
  # Project-specific exceptions
  - DL3003  # Use WORKDIR instead of cd (we use both appropriately)
  - DL3020  # Use COPY instead of ADD (we only use COPY)

# Treat warnings as errors for strict validation
failure-threshold: warning

# Enable all rules by default
override:
  error: []
  warning: []
  info: []
  style: []